version: 2.0

workspace: &workspace
             ~/code

config_android: &config_android
  docker:
    - image: circleci/android:api-29
  working_directory: *workspace
  environment:
    JAVA_TOOL_OPTIONS: "-Xmx1024m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dkotlin.incremental=false"
    TERM: dumb

update_sdk: &update_sdk
  run:
    name: Update SDK
    command: |
      yes | sdkmanager --licenses || true
      sdkmanager "platform-tools" "platforms;android-29"

decrypt_secrets: &decrypt_secrets
  run:
    name: Decrypt secrets
    command: signing/setup.sh $ENCRYPT_KEY

clean_secrets: &clean_secrets
  run:
    name: Cleanup secrets
    command: signing/cleanup.sh

jobs:
  build:
    <<: *config_android
    steps:
      - <<: *update_sdk
      - checkout
      - <<: *decrypt_secrets

      - run:
          name: Assemble release
          command: ./gradlew bundleRelease assembleRelease
      - run:
          name: Check release
          command: ./gradlew lintRelease spotlessCheck detekt dependencyUpdates

      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: build/dependencyUpdates
          destination: dependencyUpdates

      - deploy:
          name: Publish release
          command: |
            beginswith() { case $2 in "$1"*) true;; *) false;; esac; }
            if beginswith "master" "${CIRCLE_BRANCH}"; then
              ./gradlew publishRelease
            fi

      - <<: *clean_secrets
