version: 2
references:
  container_config: &container_config
    docker:
      - image: circleci/android:api-28-alpha

    working_directory: ~/code

    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1024m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dkotlin.incremental=false"
      TERM: dumb

  cache_key: &cache_key
      key: key-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    <<: *container_config
    steps:
      - checkout

      - run: ./signing/setup.sh $ENCRYPT_KEY

      - restore_cache:
          <<: *cache_key
      - run: ./gradlew app:dependencies
      - run: ./gradlew assembleRelease lintRelease
      - run: ./gradlew spotlessCheck detekt dependencyUpdates
      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle

      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: build/dependencyUpdates
          destination: dependencyUpdates

      - deploy:
          command: |
            beginswith() { case $2 in "$1"*) true;; *) false;; esac; }
            if beginswith "master" "${CIRCLE_BRANCH}"; then
              ./gradlew publishReleaseApk
            fi

      - run: ./signing/cleanup.sh
